### ISSUE TITLE
Error in the Python script

### ISSUE THREAD

**Issue by francoisschwarzentruber** [francoisschwarzentruber/cmapf-gui#4]
When I run the script 

       python3 compute.py "[1,2]" "[3,4]" 4 smallmaze.png

I get:

Traceback (most recent call last):
  File "compute.py", line 3, in <module>
    import create_graph_from_png
  File "/home/fschwarz/research/2021/cmapf-gui/create_graph_from_png.py", line 9, in <module>
    from igraph import *
  File "/usr/local/lib/python3.7/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

What does "Please upgrade when convenient." mean?

**Comment by francoisschwarzentruber** [comment]
The readme now contains the procedure in order to install the software.
